name: Reset ENVIRONMENT_CODE in UAT

on:
  push:
    branches:
      - uat

permissions:
  contents: write

jobs:
  reset-environment-variable:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: uat
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Modify Globals.cs (Reset to UAT)
        run: |
          sed -i 's/ENVIRONMENT_CODE = "PRODUCTION"/ENVIRONMENT_CODE = "UAT"/g' IM_CONSOLE_PROJECT/Globals.cs

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add IM_CONSOLE_PROJECT/Globals.cs
          git commit -m "Reset ENVIRONMENT_CODE to UAT in UAT branch"
          git push origin uat
